flowchart LR
    Assets["Assets: 1xxxxx"] --> SuspenseAccounts & CAssets & NCAssets

    SuspenseAccounts["Suspense Accounts: 100xxx"]
    CAssets["Current Assets"]  
        CAssets --> Cash["Cash and Equivalents: 101xxx"]
        CAssets --> STInvestments["Short Term Investments: 102xxx"]
        CAssets --> Receivables["Receivables: 103xxx"] 
            Receivables --> TradeReceivables["Trade Receivables: 103xxx"]
            Receivables --> StatutoryReceivables["Statutory Receivables: 103xxx"]
            Receivables --> OtherReceivables["Other Receivables: 103xxx"]
            
        CAssets --> Inventories["Inventories: 104xxx"]
        CAssets --> AccruedIncome["Accrued Income: 105xxx"]
        CAssets --> Prepayments["Prepayments: 106xxx"]

    CAssets ~~~ SuspenseAccounts
      

    NCAssets["Non Current Assets"]
        NCAssets --> LTInvestments["Long Term Investments: 107xxx"]
        NCAssets --> PPE["Property, Plant & Equipment: 108xxx"]
        NCAssets --> IntangibleAssets["Intangible Assets: 109xxx"]
        NCAssets --> ROU["Right-of-Use Assets: 110xxx"]
        NCAssets --> Goodwill["Goodwill: 111xxx"]



