flowchart LR
    %% Power users (and accounts bootstraper for non-power users) will decide whether or not to apply contra templates to "Other*" liabilities
    subgraph AdjustmentTemplate["Liabilities Adjustment Template (System Enforced)"]
        Basis["2xxxx0: Basis"]
        Adjunct["2xxxx1-8 : Adjunct"]
        Contra["2xxxx9: Contra"]
    end
    Liabilities["Liabilities: 20000 - 29999"]

    CLiabilities["Current Liabilities"]
        TradePayables["Trade Payables: 21000 - 21999"] --> AdjustmentTemplate
        StatutoryPayables["Statutory Payables: 22000 - 22999"] --> AdjustmentTemplate
        Accruals["Accrued Expenses: 23000 - 23499"] --> AdjustmentTemplate
        DeferredRevenues["Deferred Revenues: 23500 - 23999"] --> AdjustmentTemplate
        ShortTermDebts["Short Term Debts/Overdrafts: 24000 - 24999"] --> AdjustmentTemplate
        OtherCurrentLiabilities["Other Current Liabilities: 25000 - 25999"]

    NCLiabilities["Non-Current Liabilities"]
        LongTermLoan["Long Term Loans: 26000 - 26999"] --> AdjustmentTemplate
        LeaseLiabilities["Lease Liabilities: 27000 - 27999"] --> AdjustmentTemplate
        Provisions["Provisions: 28000 - 28999"] --> AdjustmentTemplate
        OtherNCL["Other Non-Current Liabilities: 29000 - 29999"]

    Liabilities --> CLiabilities & NCLiabilities

    CLiabilities --> TradePayables & StatutoryPayables & Accruals & DeferredRevenues & ShortTermDebts & OtherCurrentLiabilities
    NCLiabilities --> LongTermLoan & LeaseLiabilities & Provisions & OtherNCL
        
