flowchart LR
    %% Tracks value leaving the entity.
    %% Basis: cash drawings
    %% Adjuncts: non-cash drawings (inventory/asset)
    %% Contra: drawings reversal
    subgraph AdjustmentTemplate["Equity Adjustment Template"]
        EBasis["3xxxx0: Basis"]
        EAdjunct["3xxxx1-8 : Adjunct"]
        EContra["3xxxx9: Contra"]
    end

    Equity["Equity: 30000 - 39999"]
    Capital["Owner/Share Capital: 31000 - 31999"] --> AdjustmentTemplate
    Earnings["Retained Earnings: 32000 - 32999"] --> AdjustmentTemplate
    Reserves["Revaluation Reserves: 33000 - 33999"] --> AdjustmentTemplate
    Drawings["Drawings/Distributions: 34000 - 34999"] --> AdjustmentTemplate
    OpeningBalanceEquity["Opening Balance Equity: 3900x"]
        OBEAsset["Opening Balance Equity Asset: 39001"]
        OBELiability["Opening Balance Equity Liability: 39002"]
        OBEIncome["Opening Balance Equity Income: 39004"]
        OBEExpense["Opening Balance Equity Expense: 39005"]

    Equity --> Capital & Earnings & Reserves & Drawings & OpeningBalanceEquity
    OpeningBalanceEquity --> OBEAsset & OBELiability & OBEIncome & OBEExpense