flowchart LR
    Revenues["Revenues: 4xxxxx"]

    OperatingRevenues["Operating Revenues"]
        Sales["Sales: 400xxx"]

        ContraRevenues["Returns, Refunds & Discounts: 401xxx"]
            Returns["Returns: 401xx1"]
            Refunds["Refunds: 401xx2"]
            Discounts["Discounts: 401xx3"]

        Services["Services: 402xxx"]
        Subscriptions["Subscriptions: 403xxx"]
        EmploymentIncome["Employment Income: 404xxx"]
        
    NonOperatingRevenues["Non-Operating Revenues"]
        InterestIncome["Interest Income: 405xxx"]
        GainOnSale["Gain on Sale of Assets: 406xxx"]
        UnrealizedGains["Unrealized Gains: 407xxx"]

    Revenues --> OperatingRevenues & NonOperatingRevenues
    OperatingRevenues --> Sales & ContraRevenues & Services & Subscriptions & EmploymentIncome
    ContraRevenues --> Returns & Refunds & Discounts
    NonOperatingRevenues --> InterestIncome & GainOnSale & UnrealizedGains