flowchart LR
    Liabilities["Liabilities: 2xxxxx"]

    Liabilities --> CLiabilities & NCLiabilities & SuspenseAccounts

 
    CLiabilities["Current Liabilities"]
        CLiabilities --> ShortTermDebts["Short Term Debts/Overdrafts: 200xxx"]
        CLiabilities --> TradePayables["Trade Payables: 201xxx"]
        CLiabilities --> Accruals["Accrued Expenses: 202xxx"]
        CLiabilities --> StatutoryPayables["Statutory Payables: 203xxx"]
        CLiabilities --> DeferredRevenues["Deferred Revenues: 204xxx"]

    NCLiabilities["Non-Current Liabilities"]
        NCLiabilities --> LongTermLoan["Long Term Loans: 205xxx"]
        NCLiabilities --> LeaseLiabilities["Lease Liabilities: 206xxx"]
        NCLiabilities --> Provisions["Provisions: 207xxx"]


    %% For positioning
    NCLiabilities ~~~  SuspenseAccounts["Suspense Accounts: 299xxx"]